/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author Felipe
 */
public class TelaCalc extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalc
     */
    public TelaCalc() {
        initComponents();
        // TORNA O PAINEL INVISÍVEL
        pnlRes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNum = new javax.swing.JSpinner();
        btnCalc = new javax.swing.JButton();
        pnlRes = new javax.swing.JPanel();
        lblDiv = new javax.swing.JLabel();
        lblCubo = new javax.swing.JLabel();
        lblSqrt = new javax.swing.JLabel();
        lblCbrt = new javax.swing.JLabel();
        lblAbs = new javax.swing.JLabel();
        lblResDiv = new javax.swing.JLabel();
        lblResCubo = new javax.swing.JLabel();
        lblResSqrt = new javax.swing.JLabel();
        lblResCbrt = new javax.swing.JLabel();
        lblResAbs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculadora.png"))); // NOI18N

        jLabel2.setText("Informe um valor:");

        btnCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calc-botao.png"))); // NOI18N
        btnCalc.setText("Calcular");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        lblDiv.setText("Resto da Divisão por 2");

        lblCubo.setText("Elevado ao Cubo");

        lblSqrt.setText("Raiz Quadrada");

        lblCbrt.setText("Raiz Cúbica");

        lblAbs.setText("Valor Absoluto");

        lblResDiv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResDiv.setForeground(new java.awt.Color(0, 153, 255));
        lblResDiv.setText("0");

        lblResCubo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResCubo.setForeground(new java.awt.Color(0, 153, 255));
        lblResCubo.setText("0");

        lblResSqrt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResSqrt.setForeground(new java.awt.Color(0, 153, 255));
        lblResSqrt.setText("0");

        lblResCbrt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResCbrt.setForeground(new java.awt.Color(0, 153, 255));
        lblResCbrt.setText("0");

        lblResAbs.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResAbs.setForeground(new java.awt.Color(0, 153, 255));
        lblResAbs.setText("0");

        javax.swing.GroupLayout pnlResLayout = new javax.swing.GroupLayout(pnlRes);
        pnlRes.setLayout(pnlResLayout);
        pnlResLayout.setHorizontalGroup(
            pnlResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCbrt)
                    .addComponent(lblAbs)
                    .addComponent(lblSqrt)
                    .addComponent(lblCubo)
                    .addComponent(lblDiv))
                .addGap(30, 30, 30)
                .addGroup(pnlResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResDiv)
                    .addComponent(lblResCubo)
                    .addComponent(lblResAbs)
                    .addComponent(lblResSqrt)
                    .addComponent(lblResCbrt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlResLayout.setVerticalGroup(
            pnlResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlResLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblDiv))
                    .addComponent(lblResDiv))
                .addGap(18, 18, 18)
                .addGroup(pnlResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResCubo)
                    .addComponent(lblCubo))
                .addGap(18, 18, 18)
                .addGroup(pnlResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSqrt)
                    .addComponent(lblResSqrt))
                .addGap(18, 18, 18)
                .addGroup(pnlResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCbrt)
                    .addComponent(lblResCbrt))
                .addGap(18, 18, 18)
                .addGroup(pnlResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblResAbs)
                    .addComponent(lblAbs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(pnlRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalc)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(txtNum.getValue().toString());
        
        // RESTO DA DIVISÃO POR 2
        int resto = num % 2;
        lblResDiv.setText(Integer.toString(resto));
        
        // ELEVADO AO CUBO
        float cubo = (float) Math.pow(num, 3);
        lblResCubo.setText(Float.toString(cubo));
        
        // RAIZ QUADRADA
        float raizQ = (float) Math.sqrt(num);
        lblResSqrt.setText(String.format("%.3f", raizQ));
        
        // RAIZ CÚBICA
        float raizC = (float) Math.cbrt(num);
        lblResCbrt.setText(String.format("%.3f", raizC));
        
        // VALOR ABSOLUTO
        int mod = (int) Math.abs(num);
        lblResAbs.setText(Integer.toString(mod));
        
        // TORNA O PAINEL VISÍVEL
        pnlRes.setVisible(true);
        
    }//GEN-LAST:event_btnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAbs;
    private javax.swing.JLabel lblCbrt;
    private javax.swing.JLabel lblCubo;
    private javax.swing.JLabel lblDiv;
    private javax.swing.JLabel lblResAbs;
    private javax.swing.JLabel lblResCbrt;
    private javax.swing.JLabel lblResCubo;
    private javax.swing.JLabel lblResDiv;
    private javax.swing.JLabel lblResSqrt;
    private javax.swing.JLabel lblSqrt;
    private javax.swing.JPanel pnlRes;
    private javax.swing.JSpinner txtNum;
    // End of variables declaration//GEN-END:variables
}
